### ISSUE TITLE
conda hanging when installing a package

### ISSUE THREAD

**Issue by lowks** [UDST/ansible-conda#8]
Okay I was able to reproduce this and can point to what is causing it.

To reproduce: 
1. Create a task to install a package, eg: pillow
2. Stop the task half way by doing ctrl-C 
3. Re-run the task again. The task will hang

I found that because in the backend what is happening is conda has created a lock file that is not cleanly deleted when Ctrl-C is hit. So this causes the package install to hang while it tries to deal with the lock file. The can be seen when running conda install manually on the target host. 

What can be done is to:
1. return the error where it discovers a lock file
2. clean out lock file before attempting to install packages (might not be so good)

**Comment by jiffyclub** [comment]
This sounds like it might be a conda bug, have you checked their bug tracker for any mention of this?

**Comment by lowks** [comment]
The closest I can find is this: https://github.com/conda/conda/issues/2222

**Comment by colin-nolan** [comment]
Suggesting this is closed as it does not appear to relate to the module developed here.
